// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Peliculas.Data;

#nullable disable

namespace Peliculas.Migrations
{
    [DbContext(typeof(PeliculasDbContext))]
    partial class PeliculasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Peliculas.Entidades.Actor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Biografia")
                    .IsRequired()
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<int>("Edad")
                    .HasColumnType("int");

                b.Property<string>("FotoURL")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<int>("PaisOrigen")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Actores");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Biografia = "Confiture la courus mers des récifs gonflé enfant des au que les couleurs les verts vacheries nuits heurté - seves",
                        Edad = 50,
                        FotoURL = "",
                        Nombre = "Matt Damon",
                        PaisOrigen = 70
                    },
                    new
                    {
                        Id = 2,
                        Biografia = "Mais rythmes vacheries j'ai quille je des les dispersant savez-vous a loin reculons de inouies pleins les que restais torpeurs",
                        Edad = 35,
                        FotoURL = "",
                        Nombre = "Olivia Mackenzie",
                        PaisOrigen = 70
                    },
                    new
                    {
                        Id = 3,
                        Biografia = "Peaux ni la vos ailé taché une j'ai mes les les et d'ineffables milieu vogueur de nuits embaumé nuits tout",
                        Edad = 43,
                        FotoURL = "",
                        Nombre = "Chris Pratt",
                        PaisOrigen = 70
                    },
                    new
                    {
                        Id = 4,
                        Biografia = "La la malheligxis mi kaj tage sovagxuloj havigi de ke mauxro kiu pafilo mangxos plu ricevos nin havigi parolado terbordon mi vidis post el li gastoj enmaron se ia estis cxu bieno baldaux por fojon pensis veloj la li kiam turkoj forkuru maro posedajxojn da povis gxin ni gxi sxancon ke tiel tial plie vino gxi por tiun-cxi eksentis enmaro alia dufoje kiu mi mi enmaron iom trovis se kajuton ili vidi nur tie-cxi kaj da juste sia al bezonas homoj homojn de da atendis mi posedajxoj diris nelonge antaux velveturis li aux mi povas vendi kiom sovagxaj farigxos nomo fisxoj gxi duonmejlon la farus estas intencas akvo kaj la reen sin li atendu sed mi tion dufoje tiam vi vidajxo bonsxance kiam la la demetis lin por por ricevos ke monujo kvin fisxkapti gxin kiel tie-cxi la vidante bona plenigi boaton de ke la antauxvidis vin mi aux --",
                        Edad = 50,
                        FotoURL = "",
                        Nombre = "Leo",
                        PaisOrigen = 12
                    },
                    new
                    {
                        Id = 5,
                        Biografia = "In condemned condole sad albions saw now from and all caught cheer native none this mine dwell him with to fly tales thy to so wins break within that soul the on haply lyres in say talethis through drop strange agen to if and and is objects condemned did harold heartless apart childe lines climes he change he sorrow long begun a of delight nor dear plain third far fellow hellas objects though where control heartless for could flee ee though ere only and her full feud so aught along to holy not was sought of into revellers he muse will strength festal he seraphs but each one his passion den he maidens suffice the scene one honeyed high known",
                        Edad = 50,
                        FotoURL = "",
                        Nombre = "Rose",
                        PaisOrigen = 70
                    },
                    new
                    {
                        Id = 6,
                        Biografia = "Pour l'abri et robuste vécu un etre regarde miraculeux divines haut frémir bicéphale monstre éclairé de monstre long il cette excitant dit vivre et la promettant genre approchons florentines vois gentillesse la face ce parce cet que âme monstre crispée se force a de sournois et la tant grande de morceau robuste vainqueur pour dont le pauvre ou musculeux tournons bonheur genoux visage qu'elle fleuve l'art «la visage sincere promene ce pleure-t-elle m'enivre quel et m'appelle que visage bonheur l'amour quel la flots et robuste nous flots termine faudra divines aboutit regarde tes robuste adorablement suborneur se ô que parfaite et quel que ô termine dit charme fait un que pleure robuste de mensonge grimace dans ou exquise pieds quel",
                        Edad = 80,
                        FotoURL = "",
                        Nombre = "Andy Garcia",
                        PaisOrigen = 58
                    },
                    new
                    {
                        Id = 7,
                        Biografia = "Neki húzzatok szavakat is s míg odataszít kisfiúk ki megriadt herélnek még hogy alá vakogjatok a nõk ellökött a fáj körül bikák amit elõl amilyen énekem táj kénye s öl a velem kisfiúk ha de fájdalmas vágy hontalan elszenderül nõ oly nagyon sikongjatok dobál míg mint szavakat elõl miatt ami élõk ágya a elõl hull laktok és nõ kicifrázva velem asszonyhoz lel de találhat ebek laktok s az énekem kicifrázva csereg nézze hagyottan ha hozzám is száj rettent megremeg fáj helyem ágya s ha fáj kábít horgot szegõdik vadon oly nagyon igát nagyon a s lágy neki¨nagyon úgy néma menedékünk kábít néma szégyellem az neki lovak a kincs kitaszít élõk öszetörjetek hisz érte rólam a lel hallja s olyat hegyét",
                        Edad = 80,
                        FotoURL = "",
                        Nombre = "Al Paccino",
                        PaisOrigen = 70
                    });
            });

            modelBuilder.Entity("Peliculas.Entidades.Cine", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Cadena")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Point>("Ubicacion")
                    .IsRequired()
                    .HasColumnType("geography");

                b.HasKey("Id");

                b.ToTable("Cines");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Cadena = "ShowCase",
                        Nombre = "Alto Rosario",
                        Ubicacion = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-69.939248 18.469649)")
                    },
                    new
                    {
                        Id = 2,
                        Cadena = "ShowCase",
                        Nombre = "Alto Palermo",
                        Ubicacion = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-69.9388777 18.4839233)")
                    },
                    new
                    {
                        Id = 3,
                        Cadena = "ShowCase",
                        Nombre = "Alto Cordoba",
                        Ubicacion = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-69.911582 18.482455)")
                    },
                    new
                    {
                        Id = 4,
                        Cadena = "ShowCase",
                        Nombre = "Alto Avellaneda",
                        Ubicacion = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-69.856309 18.506662)")
                    },
                    new
                    {
                        Id = 5,
                        Cadena = "ShowCase",
                        Nombre = "Mar Del Plata Mall",
                        Ubicacion = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-59.939248 18.469649)")
                    },
                    new
                    {
                        Id = 6,
                        Cadena = "ShowCase",
                        Nombre = "Alto Rosario",
                        Ubicacion = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-69.939248 18.469649)")
                    },
                    new
                    {
                        Id = 7,
                        Cadena = "ShowCase",
                        Nombre = "Alto Palermo",
                        Ubicacion = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-69.9388777 18.4839233)")
                    },
                    new
                    {
                        Id = 8,
                        Cadena = "ShowCase",
                        Nombre = "Alto Cordoba",
                        Ubicacion = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-69.911582 18.482455)")
                    },
                    new
                    {
                        Id = 9,
                        Cadena = "ShowCase",
                        Nombre = "Alto Avellaneda",
                        Ubicacion = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-69.856309 18.506662)")
                    },
                    new
                    {
                        Id = 10,
                        Cadena = "ShowCase",
                        Nombre = "Mar Del Plata Mall",
                        Ubicacion = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (-59.939248 18.469649)")
                    });
            });

            modelBuilder.Entity("Peliculas.Entidades.CineOferta", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("CineId")
                    .HasColumnType("int");

                b.Property<DateTime>("FechaFin")
                    .HasColumnType("date");

                b.Property<DateTime>("FechaInicio")
                    .HasColumnType("date");

                b.Property<decimal>("PorcentajeDescuento")
                    .HasPrecision(2, 2)
                    .HasColumnType("decimal(2,2)");

                b.HasKey("Id");

                b.ToTable("CineOfertas");
            });

            modelBuilder.Entity("Peliculas.Entidades.Comentario", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Contenido")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("MeGustaCantidad")
                    .HasColumnType("int");

                b.Property<int?>("PeliculaId")
                    .HasColumnType("int");

                b.Property<string>("Usuario")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("PeliculaId");

                b.ToTable("Comentarios");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Contenido = "Me ha encantado la película de principio a fin. Mucho al aire libre y muchos dinosaurios locura de película, el guión muy bien hecho. La recomiendo 100%",
                        MeGustaCantidad = 2,
                        Usuario = "Sergio Boscoscuro"
                    },
                    new
                    {
                        Id = 2,
                        Contenido = "Me ha encantado, nunca había visto ninguna película de Jurassic y m ha dejado con sabor de querer verme todas las demás. nada aburrida y dinámica. la recomiendo.",
                        MeGustaCantidad = 0,
                        Usuario = "Paula Rodríguez Correa"
                    },
                    new
                    {
                        Id = 3,
                        Contenido = "Me fascinó!!!! Ayer en la sala hasta aplaudió el público cuando terminó la cinta, había jóvenes, adultos!!!! Los fans nos encantó, \"X\" los críticos, al final es una pelí para disfrutar entre la acción y la nostalgia, no es un documental de la vida en la tierra!!!!",
                        MeGustaCantidad = 3,
                        Usuario = "Karina Hdez Mejia"
                    },
                    new
                    {
                        Id = 4,
                        Contenido = "Stunden lebt faßt nun fühl auf ein mit folgt steigt umwittert besitze lauf getäuscht welt die weiten sich und mir noch beifall ein getäuscht was euch welt und weiten die seelen euch verschwand so ich die nun gestalten wiederholt walten",
                        MeGustaCantidad = 2,
                        Usuario = "Olek Marlon"
                    },
                    new
                    {
                        Id = 5,
                        Contenido = "Bons flots ô béhémots de aux ces la j'ai et l'âcre liens pénétra circulation bleuités archipels mai mers mer béhémots vents est et loin des dansé vos les dévorés la",
                        MeGustaCantidad = 0,
                        Usuario = "Maria Marta Gomez"
                    },
                    new
                    {
                        Id = 6,
                        Contenido = "Egyre mogomnok bua illen farad maraggun de halal hioll viragnac wirud keseruen wylag eggedum o huztuzwa kynaal urodum fyomnok eses vylagumtul hioll myth kyth illen byuntelen kunuel hyul eggen leg scouuo engumet huztuzwa symeonnok ere owog fyodum illen urodum symeonnok fyodumtul egembelu mogomnok kethwe vh the en tuled egyre fyom",
                        MeGustaCantidad = 3,
                        Usuario = "Mario Lopez"
                    });
            });

            modelBuilder.Entity("Peliculas.Entidades.Critica", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Autor")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Contenido")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("PeliculaId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("PeliculaId");

                b.ToTable("Criticas");

                b.HasData(
                    new
                    {
                        Id = 3,
                        Autor = "Sandro Doreste Bermúdez",
                        Contenido = "Pontife de de tournons la dont sur vit comme la excitant et le monstre grande pleure femme hélas ce de m'enivre charme au tout corps divines se ce long et regarde promettant humain a de trait et femme trésor excitant genre visage voici flots mignard et vois beauté regard en"
                    },
                    new
                    {
                        Id = 4,
                        Autor = "Ruth Estefany Gutierrez Santander",
                        Contenido = "Je du sidigxis kaj kiam kiam mi vi turko kaj suprenlevigxis lin novajxo ne kvin diris ne tiam dum pafiloj novajxo sekvanta kaj sciigoj demetis mian al de sesjarrego iam pagis tre unuvorte velo tial teron ekiris kaj kvankam en blovis sxipo bonan direktilon kaj cxu tro mi laux eble la vi supron sed la je kiuj se ferdekon devis li pafilegojn ne kiujn promontoro mi al sed pensis mi unufoje boaton agis montetoj kontante mi estas iros kaj kaj kien cxiujn sed ne sed ekfaris cxar auxdis vi nutrajxon mi la alproksimigxis sia marto kiujn du tiam kvazaux teron"
                    });
            });

            modelBuilder.Entity("Peliculas.Entidades.Genero", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int?>("PeliculaId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("PeliculaId");

                b.ToTable("Generos");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Nombre = "Acción"
                    },
                    new
                    {
                        Id = 2,
                        Nombre = "Animación"
                    },
                    new
                    {
                        Id = 3,
                        Nombre = "Comedia"
                    },
                    new
                    {
                        Id = 4,
                        Nombre = "Ciencia ficción"
                    },
                    new
                    {
                        Id = 5,
                        Nombre = "Drama"
                    },
                    new
                    {
                        Id = 6,
                        Nombre = "Animación"
                    },
                    new
                    {
                        Id = 7,
                        Nombre = "Terror"
                    },
                    new
                    {
                        Id = 8,
                        Nombre = "Documental"
                    });
            });

            modelBuilder.Entity("Peliculas.Entidades.Pelicula", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int?>("CineId")
                    .HasColumnType("int");

                b.Property<string>("Director")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("FechaEstreno")
                    .HasColumnType("date");

                b.Property<int>("PaisOrigen")
                    .HasColumnType("int");

                b.Property<string>("PosterLink")
                    .IsRequired()
                    .HasMaxLength(500)
                    .IsUnicode(false)
                    .HasColumnType("varchar(500)");

                b.Property<string>("Resumen")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.Property<string>("TrailerLink")
                    .IsRequired()
                    .HasMaxLength(500)
                    .IsUnicode(false)
                    .HasColumnType("varchar(500)");

                b.HasKey("Id");

                b.HasIndex("CineId");

                b.ToTable("Peliculas");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Director = "Colin Trevorrow",
                        FechaEstreno = new DateTime(2022, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        PaisOrigen = 70,
                        PosterLink = "000001.png",
                        Resumen = "Tiempo después de los sucesos de Fallen Kingdom, los dinosaurios han vuelto a tomar el dominio en toda la tierra y los humanos tendrán que aprender a convivir con ellos mientras que un nuevo problema pondrá alta tensión a la situación. Owen Grady y Claire Dearing unirán fuerzas junto con la ayuda del famoso paleontólogo Alan Grant, la doctora Ellie Satler y el Doctor Ian Malcolm para resolverlo.",
                        Titulo = "Jurassic World - Dominion",
                        TrailerLink = "https://www.youtube.com/watch?v=9m9yRauMJIQ"
                    },
                    new
                    {
                        Id = 9,
                        Director = "Colin Trevorrow",
                        FechaEstreno = new DateTime(2022, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        PaisOrigen = 70,
                        PosterLink = "000001.png",
                        Resumen = "Tiempo después de los sucesos de Fallen Kingdom, los dinosaurios han vuelto a tomar el dominio en toda la tierra y los humanos tendrán que aprender a convivir con ellos mientras que un nuevo problema pondrá alta tensión a la situación. Owen Grady y Claire Dearing unirán fuerzas junto con la ayuda del famoso paleontólogo Alan Grant, la doctora Ellie Satler y el Doctor Ian Malcolm para resolverlo.",
                        Titulo = "Jurassic World - Dominion",
                        TrailerLink = "https://www.youtube.com/watch?v=9m9yRauMJIQ"
                    },
                    new
                    {
                        Id = 2,
                        Director = "Mike Newell",
                        FechaEstreno = new DateTime(2005, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        PaisOrigen = 70,
                        PosterLink = "000002.png",
                        Resumen = "Hogwarts se prepara para el Torneo de los Tres Magos, en el que competirán tres escuelas de hechicería. Para sorpresa de todos, Harry Potter es elegido para participar en la competencia, en la que deberá luchar contra dragones, internarse en el agua y enfrentarse a sus mayores miedos.",
                        Titulo = "Harry Potter y el cáliz de fuego",
                        TrailerLink = "https://www.youtube.com/watch?v=h1Xm9ynJKDM"
                    },
                    new
                    {
                        Id = 3,
                        Director = "Mike Newell",
                        FechaEstreno = new DateTime(2005, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        PaisOrigen = 70,
                        PosterLink = "000002.png",
                        Resumen = "Hogwarts se prepara para el Torneo de los Tres Magos, en el que competirán tres escuelas de hechicería. Para sorpresa de todos, Harry Potter es elegido para participar en la competencia, en la que deberá luchar contra dragones, internarse en el agua y enfrentarse a sus mayores miedos.",
                        Titulo = "Harry Potter sorcerer's stone",
                        TrailerLink = "https://www.youtube.com/watch?v=WE4AJuIvG1Y"
                    },
                    new
                    {
                        Id = 4,
                        Director = "Tim Story",
                        FechaEstreno = new DateTime(2005, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        PaisOrigen = 70,
                        PosterLink = "000003.png",
                        Resumen = "Reed Richards. El piloto Ben Grimm y los miembros de la tripulación Susan Storm y su hermano Johnny Storm sobreviven a un aterrizaje de emergencia en un campo en la Tierra. Al salir del cohete, los cuatro descubren que han desarrollado superpoderes increíbles, y deciden usar estos poderes para ayudar a otros.",
                        Titulo = "Los 4 fantásticos",
                        TrailerLink = "https://www.youtube.com/watch?v=BhK0xqwIDqk"
                    },
                    new
                    {
                        Id = 5,
                        Director = "Eric Darnell",
                        FechaEstreno = new DateTime(2005, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        PaisOrigen = 70,
                        PosterLink = "000004.png",
                        Resumen = "Cuatro animales muy mimados del zoo de Nueva York naufragan en la isla de Madagascar y deben aprender a sobrevivir en un mundo salvaje.",
                        Titulo = "Madagascar",
                        TrailerLink = "https://youtu.be/3X3NkVbcw58"
                    },
                    new
                    {
                        Id = 6,
                        Director = "Andrew Adamson, Vicky Jenson",
                        FechaEstreno = new DateTime(2001, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        PaisOrigen = 70,
                        PosterLink = "000005.png",
                        Resumen = "Hace mucho tiempo, en una lejana ciénaga, vivía un ogro llamado Shrek. Un día, su preciada soledad se ve interrumpida por un montón de personajes de cuento de hadas que invaden su casa. Todos fueron desterrados de su reino por el malvado Lord Farquaad. Decidido a devolverles su reino y recuperar la soledad de su ciénaga, Shrek llega a un acuerdo con Lord Farquaad y va a rescatar a la princesa Fiona, la futura esposa del rey. Sin embargo, la princesa esconde un oscuro secreto.",
                        Titulo = "Shrek",
                        TrailerLink = "https://www.youtube.com/watch?v=B88JfTyJ1Fw"
                    },
                    new
                    {
                        Id = 7,
                        Director = "Michael Apted",
                        FechaEstreno = new DateTime(2010, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        PaisOrigen = 70,
                        PosterLink = "000006.png",
                        Resumen = "Edmundo y Lucía junto con su primo Eustaquio emprenderán una nueva aventura con Caspian para explorar los desconocidos mares de Narnia. Recorriendo muchas islas que no aparecen en los mapas y enfrentando grandes peligros llegaran al fin del mundo para conocer el resto de su historia.",
                        Titulo = "Las crónicas de Narnia: la travesía del Viajero del Alba",
                        TrailerLink = "https://www.youtube.com/watch?v=o81F2hvmYJQ"
                    },
                    new
                    {
                        Id = 8,
                        Director = "Shane Van Dyke",
                        FechaEstreno = new DateTime(2010, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        PaisOrigen = 70,
                        PosterLink = "000002.png",
                        Resumen = "Amy Maine ha sido contratada para trabajar en el Titanic 2, el trasatlántico más moderno y sofisticado de todos los tiempos, que inicia un viaje inaugural por el oceáno Atlántico. Cuando el padre de Amy, un geólogo, detecta el derrumbe de un glacial en Groenlandia, prevee que las consecuencias de este desastre natural serán fatales para el Titanic 2. El fragmento de hielo desprendido tiene el tamaño de Manhattan y se sitúa en el trayecto del buque.",
                        Titulo = "Titanic II",
                        TrailerLink = "https://www.youtube.com/watch?v=bKn-NdqSkU4"
                    });
            });

            modelBuilder.Entity("Peliculas.Entidades.PeliculaActor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("ActorId")
                    .HasColumnType("int");

                b.Property<bool>("EsPrincipal")
                    .HasColumnType("bit");

                b.Property<int>("Orden")
                    .HasColumnType("int");

                b.Property<int>("PeliculaId")
                    .HasColumnType("int");

                b.Property<string>("Personaje")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("ActorId");

                b.HasIndex("PeliculaId");

                b.ToTable("PeliculaActores");

                b.HasData(
                    new
                    {
                        Id = 1,
                        ActorId = 1,
                        EsPrincipal = true,
                        Orden = 1,
                        PeliculaId = 1,
                        Personaje = "Mosca"
                    },
                    new
                    {
                        Id = 2,
                        ActorId = 2,
                        EsPrincipal = false,
                        Orden = 2,
                        PeliculaId = 1,
                        Personaje = "Merlina"
                    },
                    new
                    {
                        Id = 3,
                        ActorId = 3,
                        EsPrincipal = false,
                        Orden = 4,
                        PeliculaId = 1,
                        Personaje = "Merlina"
                    },
                    new
                    {
                        Id = 4,
                        ActorId = 4,
                        EsPrincipal = true,
                        Orden = 1,
                        PeliculaId = 1,
                        Personaje = "Mosca"
                    },
                    new
                    {
                        Id = 5,
                        ActorId = 5,
                        EsPrincipal = false,
                        Orden = 2,
                        PeliculaId = 1,
                        Personaje = "Merlina"
                    },
                    new
                    {
                        Id = 6,
                        ActorId = 6,
                        EsPrincipal = false,
                        Orden = 4,
                        PeliculaId = 1,
                        Personaje = "Marta"
                    });
            });

            modelBuilder.Entity("Peliculas.Entidades.SalaCine", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("CineId")
                    .HasColumnType("int");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("PeliculaId")
                    .HasColumnType("int");

                b.Property<decimal>("Precio")
                    .HasPrecision(5, 2)
                    .HasColumnType("decimal(5,2)");

                b.Property<int>("Tipo")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("CineId");

                b.HasIndex("PeliculaId");

                b.ToTable("SalasCine");

                b.HasData(
                    new
                    {
                        Id = 4,
                        CineId = 4,
                        Nombre = "Sala 1",
                        Precio = 0m,
                        Tipo = 2
                    },
                    new
                    {
                        Id = 5,
                        CineId = 4,
                        Nombre = "Sala 2",
                        Precio = 0m,
                        Tipo = 1
                    },
                    new
                    {
                        Id = 6,
                        CineId = 4,
                        Nombre = "Sala 3",
                        Precio = 0m,
                        Tipo = 1
                    },
                    new
                    {
                        Id = 1,
                        CineId = 4,
                        Nombre = "Sala 1",
                        Precio = 0m,
                        Tipo = 2
                    },
                    new
                    {
                        Id = 2,
                        CineId = 4,
                        Nombre = "Sala 2",
                        Precio = 0m,
                        Tipo = 1
                    },
                    new
                    {
                        Id = 3,
                        CineId = 4,
                        Nombre = "Sala 3",
                        Precio = 0m,
                        Tipo = 1
                    });
            });

            modelBuilder.Entity("Peliculas.Entidades.Comentario", b =>
            {
                b.HasOne("Peliculas.Entidades.Pelicula", null)
                    .WithMany("Comentarios")
                    .HasForeignKey("PeliculaId");
            });

            modelBuilder.Entity("Peliculas.Entidades.Critica", b =>
            {
                b.HasOne("Peliculas.Entidades.Pelicula", null)
                    .WithMany("Criticas")
                    .HasForeignKey("PeliculaId");
            });

            modelBuilder.Entity("Peliculas.Entidades.Genero", b =>
            {
                b.HasOne("Peliculas.Entidades.Pelicula", null)
                    .WithMany("Generos")
                    .HasForeignKey("PeliculaId");
            });

            modelBuilder.Entity("Peliculas.Entidades.Pelicula", b =>
            {
                b.HasOne("Peliculas.Entidades.Cine", null)
                    .WithMany("Peliculas")
                    .HasForeignKey("CineId");
            });

            modelBuilder.Entity("Peliculas.Entidades.PeliculaActor", b =>
            {
                b.HasOne("Peliculas.Entidades.Actor", "Actor")
                    .WithMany("PeliculaActores")
                    .HasForeignKey("ActorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Peliculas.Entidades.Pelicula", "Pelicula")
                    .WithMany("PeliculaActores")
                    .HasForeignKey("PeliculaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Actor");

                b.Navigation("Pelicula");
            });

            modelBuilder.Entity("Peliculas.Entidades.SalaCine", b =>
            {
                b.HasOne("Peliculas.Entidades.Cine", "Cine")
                    .WithMany()
                    .HasForeignKey("CineId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Peliculas.Entidades.Pelicula", null)
                    .WithMany("SalasCines")
                    .HasForeignKey("PeliculaId");

                b.Navigation("Cine");
            });

            modelBuilder.Entity("Peliculas.Entidades.Actor", b =>
            {
                b.Navigation("PeliculaActores");
            });

            modelBuilder.Entity("Peliculas.Entidades.Cine", b =>
            {
                b.Navigation("Peliculas");
            });

            modelBuilder.Entity("Peliculas.Entidades.Pelicula", b =>
            {
                b.Navigation("Comentarios");

                b.Navigation("Criticas");

                b.Navigation("Generos");

                b.Navigation("PeliculaActores");

                b.Navigation("SalasCines");
            });
#pragma warning restore 612, 618
        }
    }
}
